
service: base-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  profile: base-service-${self:provider.stage}
  apiGateway: 
    shouldStartNameWithService: true
    description: A set of services
  environment:
    stage: ${self:provider.stage}
    AWS_PROFILE: base-service-${self:provider.stage} # allows sls offline to read aws profile
    STATIC_FILES_PATH: static-files

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  serverless-offline:
    useChildProcesses: true
    port: 9229
  webpack:
    includeModules: true

functions:
  config:
    handler: src/handlers/config.get
    events:
    - http:
        path: config
        private: false
        method: get


